### ISSUE TITLE
toImmutableRoaringBitmap() is a bit misleading

### ISSUE THREAD

**Issue by trejkaz** [RoaringBitmap/RoaringBitmap#170]
On the surface a call to `MutableRoaringBitmap#toImmutableRoaringBitmap()` would seem to be converting to an immutable bitmap, but all it actually does is a cast.

This creates the opportunity to create bugs, where someone discovers the set is actually mutable and casts back to it, mutating the set.

I think this method should do a copy into a new immutable set, or be removed.

**Comment by lemire** [comment]
The specification of the method is 

```
   * Convenience method, effectively casts the object to an object of class ImmutableRoaringBitmap.
   *
   *
   * This function is equivalent to :
   *
   * <pre>
   * {@code
   *       (ImmutableRoaringBitmap) bitmap
   * }
   * </pre>
   * @return a cast of this object
```

Of course, one may think it does something else before reading the specification, but the API's job is to push you in the right direction...

We get to the next point, making a copy as you suggest is actively discouraged because it creates a bitmap that has significantly reduced performance. The ImmutableRoaringBitmap is meant to be used over memory-mapped files, not to be used over bitmaps that fit in Java's heap.

In any case, this is worth documenting so I have added the following commentary to the function specification:

https://github.com/RoaringBitmap/RoaringBitmap/commit/3d70e3e96f62f4f70481e1b54a92ce13274ab81c

**Comment by trejkaz** [comment]
So is there not an immutable implementation that also fits in the heap? I don't really want any mutable types in the system if I can help it.

**Comment by lemire** [comment]
@trejkaz  

>So is there not an immutable implementation that also fits in the heap?

Because an ImmutableRoaringBitmap access the data through a ByteBuffer, the data can reside wherever you want. However, accessing data through a ByteBuffer comes with a significant performance penalty, so I discourage doing so unless it is really needed.

There is the secondary problem that there are many ways to create an instance of a ByteBuffer, and it is not clear which approach is best... so you need to make a conscious decision as to where your bitmaps will reside.

If it is needed, then you can use the code documented in this commit https://github.com/RoaringBitmap/RoaringBitmap/commit/3d70e3e96f62f4f70481e1b54a92ce13274ab81c

**Comment by trejkaz** [comment]
I do still have one concern with all this, and it relates to the second option I gave for resolving the problem - deleting the method. If the method doesn't work as the name suggests, can't it just be removed?

As far as I can see, there is no valid case for calling this method at present. It only serves to encourage people to call it mistakenly.
Even if I wanted to use a `MutableRoaringBitmap` as an "immutable" one, I could just do this:

    MutableRoaringBitmap mutable = createMutable();
    ImmutableRoaringBitmap immutable = mutable;

**Comment by lemire** [comment]
The library is in widespread use so we want avoid breaking the existing API.

**Comment by trejkaz** [comment]
Java has this thing called "deprecation".

**Comment by lemire** [comment]
You'd want to deprecate it in favor of some other alternative otherwise the deprecation only adds an annoying warning that has to be ignored. In the general case, given the current code base, there is no better alternative... that is no option that does not significantly affect performance.

Now... if you are interested in helping out by coding and helping to maintain such an efficient alternative...

**Comment by lemire** [comment]
And before you reply... have people cast... this was tried... we added this method precisely to help out the folks who kept asking how they could get an ImmutableRoaringBitmap from a MutableRoaringBitmap. The method has the stated purpose in its description... it helps people find the most efficient way to get an ImmutableRoaringBitmap.

**Comment by trejkaz** [comment]
What I'm saying is that you should deprecate the method there right now, with no replacement.

Having dangerous misleading methods in APIs is not helpful.

And all this "existing code" you talk about which might be calling this method? It's all buggy, _because_ it's calling this method.

**Comment by trejkaz** [comment]
The method does not even return an immutable bitmap. It's faulty. Either fix your shit, or delete it. Stop making excuses for broken code.

**Comment by lemire** [comment]
I don't think there is any need to use vulgar language. 


This method does exactly what its specification describes, if you disagree please provide a test.

The method does not do what you'd like it to do, but I think I explained why it requires work to provide this better alternative without performance penalty.

If you submit a PR with code that provides a superior way to create an ImmutableRoaringBitmap from a MutableRoaringBitmap we'll eagerly adopt it.

**Comment by trejkaz** [comment]
You don't appear to be listening, but I'll say it again:

Just delete the method. You don't need an alternative because one is already an instance of the other.

Please learn the Java language. Also, please learn what "immutable" is supposed to mean, because none of this supposedly "immutable" stuff is actually compliant with the usual definition.

**Comment by trejkaz** [comment]
Mind you, MutableRoaringBitmap extending ImmutableRoaringBitmap is a faulty design decision too, so maybe there is just no way for this library to fix itself without a complete redesign.
