### ISSUE TITLE
To support concatenate two RoaringBitmaps into one

### ISSUE THREAD

**Issue by shshen** [RoaringBitmap/RoaringBitmap#194]
We have a lot of code depending on `concat(RoaringBitmap x1, int x1_length, RoaringBitmap x2).`
For now, I'm using `x2.forEach` to iterate all values, and then set to x1 plus offset x1_length.    Is there any faster way to add an offset to all x2 values?  then i could concatenate two RoaringBitmap together

**Comment by lemire** [comment]
The gist of it is that this would be easy to implement efficiently when ``x1_length`` is divisible by 65536. However, @shshen wants support for the general case. This is reasonable but an efficient implementation is maybe not trivial.

Help is needed to implement this feature. A pull request is invited.

**Comment by gssiyankai** [comment]
Supporting the shift operator would be a step closer to the optimal
implementation.

**Comment by lemire** [comment]
Excellent. I might get around to implementing it, but it would go faster if someone were to volunteer.

**Comment by lemire** [comment]
@gssiyankai  You are quite right. A shift would do the job. It is quite reasonable. It is not super hard to do.

Not on my todo right now, sadly, I cannot afford it.

If someone wants to jump in...?

I'll try to add it to my todo if nobody jumps in for a while.

**Comment by gssiyankai** [comment]
@lemire
Unfortunately I don't have my toolset to work on it for the time being...
I also need to allocate some time to review the latest PRs. I think there
is an issue with the changes on the project structure and pom refactoring.

On Dec 13, 2017 4:29 AM, "Daniel Lemire" <notifications@github.com> wrote:

@gssiyankai <https://github.com/gssiyankai> You are quite right. A shift
would do the job. It is quite reasonable. It is not super hard to do.

Not on my todo right now, sadly, I cannot afford it.

If someone wants to jump in...?

I'll try to add it to my todo if nobody jumps in for a while.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/RoaringBitmap/RoaringBitmap/issues/194#issuecomment-351271618>,
or mute the thread

**Comment by richardstartin** [comment]
@gssiyankai 

How are you thinking of doing this? A shift by a multiple of 65536 can be done without copying any containers, you just reindex the high-low container. If you were to start again, you could do copyless arbitrary shifts by adding an `int` offset to `RoaringBitmap` and just return a new `RoaringBitmap` with the new offset, without even copying the high low container. Then, for methods like `add`, `contains` etc. you add this offset to the input parameter before splitting into the key and short. I think this would be quite difficult to retrofit though, especially for things like `or` and `and`, and you're likely to miss some cases.

**Comment by gssiyankai** [comment]
@richard,
You summarized what I was thinking about.
I would go with the simplest solution that consists in materializing a new
bitmap with new containers. It would be more efficient than iterating over
all values anyway.


On Dec 13, 2017 1:04 PM, "Richard Startin" <notifications@github.com> wrote:

@gssiyankai <https://github.com/gssiyankai>

How are you thinking of doing this? A shift by a multiple of 65536 can be
done without copying any containers, you just reindex the high-low
container. If you were to start again, you could do copyless arbitrary
shifts by adding an int offset to RoaringBitmap and just return a new
RoaringBitmap with the new offset, without even copying the high low
container. Then, for methods like add, contains etc. you add this offset to
the input parameter before splitting into the key and short. I think this
would be quite difficult to retrofit though, especially for things like or
and and, and you're likely to miss some cases.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/RoaringBitmap/RoaringBitmap/issues/194#issuecomment-351372091>,
or mute the thread

**Comment by richardstartin** [comment]
@gssiyankai 

I really like the idea of being able to do a zero copy shift + merge of what could be zero-indexed partitions of some larger structure, to get a top level view. I am going to experiment with that in a toy project rather than directly in the source code here.

**Comment by lemire** [comment]
This is still open. It would be great if someone would volunteer. It does not look like I'll get to it anytime soon.

**Comment by lemire** [comment]
@shshen @richardstartin @gssiyankai

I added a ``RoaringBitmap.addOffset`` function which basically "shifts" add the data by a bitset. Do this followed by union (``or``) and you can concatenate bitmaps together. This ought to be super fast. My code is not highly optimized so there are further gains possible, but compared with a call to ``forEach``, it should be ridiculously faster.

```
    RoaringBitmap result = new RoaringBitmap();
    for(int i = 0; i < bitSets.length; ++i) {
      RoaringBitmap shifted = RoaringBitmap.addOffset(bitSets[i].bitmap, bitSets[i].offset);
      result.or(shifted);
    }
    return result;
```

I'll issue a release soon.

**Comment by lemire** [comment]
Fast concatenation is available as of release 0.7.11.

**Comment by brucenan** [comment]
the value of offset should only be >0 ?

**Comment by lemire** [comment]
@brucenan That's correct. In an upcoming release, we will throw an exception if the offset is negative.
