### ISSUE TITLE
method select(j) throws Exception

### ISSUE THREAD

**Issue by AlstonWilliams** [RoaringBitmap/RoaringBitmap#203]
Version: 0.6.51
JDK: 1.8.0_151
JUnit: 4.10

I have initialized a **RoaringBitmap** instance, and called method **add(3)**.  And the result I got from method **last()** is also **3**. But when I called **select(3)** to get the value of this position, it throws a en exception **java.lang.IllegalArgumentException: select 3 when the cardinality is 1**. I read the source code of method **select()**, but I don't know why it checks cardinality.

All the way, the behaviour is not consistent between these two method. And it is very confusing because there is not so many documentations for beginners to start with. In fact, I can just find the API doc. And the API doc hasn't warn this behaviour.

`import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.roaringbitmap.RoaringBitmap;

public class TestRoaringBitmap {

  private RoaringBitmap roaringBitmap = new RoaringBitmap();

  @Before
  public void setup() {
    roaringBitmap.add(3);
  }

  @Test
  public void testRoaringBitmapLastWhenRoaringBitmapJustContainElementInIndex3() {
    Assert.assertEquals(3, roaringBitmap.last());
  }

  @Test
  public void testRoaringBitmapSelect3() {
    Assert.assertEquals(1, roaringBitmap.select(3));
  }

}`

**Comment by richardstartin** [comment]
Hi, select(i) gives you the ith element. So if you call select(0) it should give you 3, and select(1) will also throw.

**Comment by lemire** [comment]
Thank you. I have just committed code that will return a more expressive error message.

@richardstartin  is right.


A selection is a technical term that refers to the ith value. That's also what the javadoc indicates. I agree that the error message was suboptimal... I think  I improved that. 

Myself, I am often confused between rank and select. It is possible that you are looking for the "rank" method. Note that indexes start at 0, which is standard in Java... so that the rank of 3 in your case is 0.

The rank and select terminology is standard... it is not something specific to Roaring. It comes from statistics.

>  the behaviour is not consistent between these two method

As far as I can tell, these methods do what the documentation says they do. If you disagree, please elaborate. 

We'd be very interested in resolving any perceived inconsistency.

> And it is very confusing because there is not so many documentations for beginners to start with. In fact, I can just find the API doc. And the API doc hasn't warn this behaviour.

The API doc stated that select would return the ith value. 

It is true that there is not a lot of documentation for beginners. We are a community-supported project so if you want to contribute documentation, we would like that.

**Comment by lemire** [comment]
I'm closing this issue, please reopen if you disagree.

**Comment by AlstonWilliams** [comment]
Hello,

      I think maybe there is a misunderstanding.

      I always think Bitmap is an bit array, which means that, if I call method `add(3)`, then the element at index 0, 1 and 2 should be 0, but the element at index 3 should be 1.

      So, I think I should get 1 when I call `select(3)`. But get 0 when I call `select(0/1/2)`.

      Maybe just store the element whose value is 1 to reduce the memory?

      Thank you.


________________________________
发件人: Daniel Lemire <notifications@github.com>
发送时间: 2018年1月17日 14:58
收件人: RoaringBitmap/RoaringBitmap
抄送: Alston Williams; Author
主题: Re: [RoaringBitmap/RoaringBitmap] method select(j) throws Exception (#203)


Thank you. I have just committed code that will return a more expressive error message.

@richardstartin<https://github.com/richardstartin> is right.

A selection is a technical term that refers to the ith value. That's also what the javadoc indicates. I agree that the error message was suboptimal... I think I improved that.

Myself, I am often confused between rank and select. It is possible that you are looking for the "rank" method. Note that indexes start at 0, which is standard in Java... so that the rank of 3 in your case is 0.

The rank and select terminology is standard... it is not something specific to Roaring. It comes from statistics.

the behaviour is not consistent between these two method

As far as I can tell, these methods do what the documentation says they do. If you disagree, please elaborate.

We'd be very interested in resolving any perceived inconsistency.

And it is very confusing because there is not so many documentations for beginners to start with. In fact, I can just find the API doc. And the API doc hasn't warn this behaviour.

The API doc stated that select would return the ith value.

It is true that there is not a lot of documentation for beginners. We are a community-supported project so if you want to contribute documentation, we would like that.

―

**Comment by lemire** [comment]
If you want to know whether '3' is part of the set after calling 'add(3)', you can call 'contains(3)'.
