### ISSUE TITLE
Evaluate performance of a bitmap.NextMany() functionality 

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#221]
It appears that we are getting good performance in Go with a bitmap.NextMany() function, to iterate in bulk over set values.

https://github.com/RoaringBitmap/roaring/pull/150

**Comment by lemire** [comment]
c.c. @richardstartin

**Comment by richardstartin** [comment]
I took a look. Is the idea to write the next `n` elements onto a fixed length `int[]`, instead of one call to `next()` for each value? I think that would be quick to prototype and should be extremely fast if you just need to get hold of the integers quickly. But there's an alternative aspect to this which is what the calling code does. If the next `n` integers are scattered, some code may not profit from optimisation opportunities available with iterators which can transfer control to the caller for entire runs.

**Comment by lemire** [comment]
@richardstartin 

>  Is the idea to write the next n elements onto a fixed length int[], instead of one call to next() for each value?

Yes.

> But there's an alternative aspect (...)

Even if it works fast, it still not going to be appropriate for all applications. It would be an option the developer can take.

**Comment by lemire** [comment]
@richardstartin Great.
