### ISSUE TITLE
RoaringBitmapParent artefact published

### ISSUE THREAD

**Issue by ppiotrow** [RoaringBitmap/RoaringBitmap#222]
https://mvnrepository.com/artifact/org.roaringbitmap/RoaringBitmapParent
Should this be really published?

**Comment by lemire** [comment]
I have a whole nasty rant against this artefact

https://github.com/RoaringBitmap/RoaringBitmap/issues/197

I think it is ugly and smells like a hack.

But we have very smart folks working on this library and they have me convinced that it is the way to go.

So that’s where we stand.

If you want to argue against this artefact, you’ll need to review and rebut the case for its addition.

It was not a frivolous change.

Closing... reopen if you have a case to make.
