### ISSUE TITLE
Support previousValue, nextAbsentValue, and previousAbsentValue

### ISSUE THREAD

**Issue by incaseoftrouble** [RoaringBitmap/RoaringBitmap#282]
Hi,

Both `BitSet` and `SparseBitSet` have said functions, which return the next / previous index which is contained / not contained in the set. All of them should be rather easy to implement I guess, since they are very similar to nextValue / (reverse) iterators.

I'm using roaring bitmaps in a [library](https://github.com/incaseoftrouble/naturals-util) abstracting data structures used to represent sets of natural numbers. Among other things, the library offers complement views on such sets, where the role of present and absent values is flipped. Naturally, such a "next/previousAbsentValue" is useful in this context.

**Comment by richardstartin** [comment]
Prefix compression makes nextValue quite expensive compared to using iterators, traversing the bitmap becomes O(n log c) where n is the number of bits and c is the number of containers. Storing the state of the current position within the bitmap eliminates the O(log c) factor, so using an iterator is advantageous if applicable.

Incidentally, bidirectional iterators would be interesting.

**Comment by lemire** [comment]
@richardstartin  is right.


Performance-wise, it is not a great idea to implement what you propose. There is a reason why we abstract the access through an iterator: the iterator preserves the necessary information to quickly move through the values.

To see why it might be a problem, consider a sorted list of integers. You can find any value in the list in time O(log n). And it is a bad kind of O(log n), one that is made of cache misses, so it is genuinely expensive (memory bound). But what if you want to find the value next to some some target value? It is again O(log n). 

A much more reasonable implement is to track the location of the value in the array and just increment or decrement the location. Then you get constant-time operations, with minimal cache misses.

For an uncompress ``BitSet``, it is much more reasonable because access to the storage location of a known value is constant-time so for a sufficiently dense ``BitSet``, finding the location next to another target location is also constant time... it is fast...

Still, if someone wants to implement these functions and contribute them, they maybe acceptable as long as it is understood that they may be slow. We would have to carefully document them and discourage their use in performance sensitive contexts.




Note that this discussion is entirely general. If you want to iterate over the rows on a database in SQL, you don't do it but asking which row follows the row you are currently holding. If you want to iterate over the values in a b-tree, you don't ask for the value next to the value you are holding. These are basically anti-patterns as far as efficiency is concerned.

**Comment by incaseoftrouble** [comment]
I'm aware that these operations are slower, I guess practically anything which is not a bulk-operation is rather slow in comparison. I don't plan to use those operations iteratively, e.g., calling `nextValue` repeatedly to iterate through the map. On the other hand, I'm developing a library so people may misuse it anyway...

To concretize, one of my applications is as follows: I provide a "bounded set" interface which is given a domain size and uses an bitmap to represent present values. These sets provide a natural constant time complementation (by simply inverting the interpretation of present and absent indices). For these sets, it is interesting to compute, e.g., the first and last "set" bit, which equates to the first absent bit and the last absent bit smaller than the domain size for the case of complemented sets.

In line with @richardstartin comment: It might be interesting to have bidirectional iterators which can be initialized to a particular position (giving you a one-time log n and then the sort-of constant time increments)?

I know that my use case might (probably is) very specific, so it may not be worth implementing this feature if no one else needs it. `BitSet` and `SparseBitSet` offer these features, so I suspected there might be some users.

**Comment by lemire** [comment]
It is not unreasonable, certainly, if one is aware of the performance limitations.

Yes, we would like to have bidirectional iterators that can be initialized from any given starting point. I just created this as a new issue.

**Comment by richardstartin** [comment]
An iterator that starts off at an arbitrary position would be very useful in stateless applications.

**Comment by incaseoftrouble** [comment]
Thanks a lot! I'll try to have a look at the clear bit thing in the near future.

**Comment by lemire** [comment]
Great. Let us keep this issue opened until it is fully resolved.

**Comment by incaseoftrouble** [comment]
Sorry this took so long, got caught up in some research projects ...
