### ISSUE TITLE
It is no longer possible to create new releases of RoaringBitmap (gradle)

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#392]
Upgrading to gradle 6 broke our release process:

```
$ ./gradlew  release

> Task :release FAILED
Release process failed, reverting back any changes made by Release Plugin.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':release'.
> Included build in /home/dlemire/CVS/github/RoaringBitmap has name 'RoaringBitmap' which is the same as a project of the main build.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.3/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 590ms
1 actionable task: 1 executed
```

It may be due to https://github.com/gradle/gradle/issues/11301

**Comment by lemire** [comment]
cc @richardstartin

**Comment by lemire** [comment]
@marshallpierce Can you help? I have zero clue as to what to do or why this would ever fail?

**Comment by lemire** [comment]
Ok. Here is the solution...

```
cd ..
mv RoaringBitmap gradleisashamefulpieceofcrap
cd gradleisashamefulpieceofcrap
./gradlew  release 
```

and it works.

This is really not good. Really not good.

**Comment by lemire** [comment]
I don't understand how anyone gets any work done with an infrastructure like this.

**Comment by lemire** [comment]
I am still screaming and rolling on the floor. I just wasted 30 mins on this. WTF.

**Comment by marshallpierce** [comment]
Hmm, that is a frustrating bug... I haven't seen that before, and I have other projects on gradle 6.3 that I have released, though none with the exact structure that this project has. The release plugin has a corresponding issue: https://github.com/researchgate/gradle-release/issues/330

It's entirely possible to ditch the release plugin since it seems to be interacting poorly with whatever that gradle composite build issue is doing. All it's doing is bumping the `version` property in gradle.properties and generating consistent commit messages and a git tag. If you're comfortable doing that yourself, that is 100% viable -- just invoke the `bintrayUpload` task when you're on the tagged `1.2.3` commit with the `version` property set to `1.2.3`, and then go to `1.2.4-SNAPSHOT` in the next commit (or whatever).

If I get a chance I'll look around for other plugins that might offer the same functionality as the `release` plugin  to get back to the nice "one command does it all" end state.

**Comment by lemire** [comment]
@marshallpierce Thanks. 

My workaround is nice enough. It just took me a lot of time to come up with it.
