### ISSUE TITLE
Roaring64Bitmap::and does not filter correctly

### ISSUE THREAD

**Issue by AChekroun** [RoaringBitmap/RoaringBitmap#428]
**Describe the bug**
Roaring64Bitmap::and does not work as expected

**To Reproduce**

Version tested: 0.9.0 & 0.9.4 
```
    @Test
    public void testRB(){
        long input = 1353768194141061120L;

        long[] compare = new long[]{
            5192650370358181888L,
            5193776270265024512L,
            5194532734264934400L,
            5194544828892839936L,
            5194545653526560768L,
            5194545688960040960L,
            5194545692181266432L,
            5194545705066168320L,
            5194545722246037504L,
            5194545928404467712L,
            5194550326450978816L,
            5194620695195156480L,
            5206161169240293376L
        };

        Roaring64Bitmap inputRB = new Roaring64Bitmap();
        inputRB.add(input);

        Roaring64Bitmap compareRB = new Roaring64Bitmap();
        compareRB.add(compare);

        // Test
        compareRB.and(inputRB);

        // Should be empty
        // Currently returns 9
        assertEquals(0, compareRB.getIntCardinality());

    }
```

**Java version:**

12.0.1

Thanks for your time

**Comment by lemire** [comment]
@weijie Can you have a look?

**Comment by weijietong** [comment]
Ok, I will fixed later. The reason is we have logic bugs to implement the `AbstractShuttle`. The initial intention is to use stack to hold the traversed path to accelerate the iterating speed. But when the remove operations happen, the `ART` tree will be changed. The stack will hold some invalid state data. Though I was conscious that while implemented the `remove` by replacing the top node of the stack to a fresh one. It still has other invalid state data like the node's position.

So I will reimplement the `AbstractShuttle` to abandon the stack strategy. But it's weekend, my macbook has very little power  to finish the PR now. So the fixed PR will be ok next week.  Also it will be appreciated if someone could take this as soon as possible.

**Comment by lemire** [comment]
Thank you. We will issue a new release soon after you have submitted a patch.

**Comment by caoxiaoyuan7242** [comment]
> Ok, I will fixed later. The reason is we have logic bugs to implement the `AbstractShuttle`. The initial intention is to use stack to hold the traversed path to accelerate the iterating speed. But when the remove operations happen, the `ART` tree will be changed. The stack will hold some invalid state data. Though I was conscious that while implemented the `remove` by replacing the top node of the stack to a fresh one. It still has other invalid state data like the node's position.
> 
> So I will reimplement the `AbstractShuttle` to abandon the stack strategy. But it's weekend, my macbook has very little power to support me to finish the PR now. So the fixed PR will be ok next week. Also it will be appreciated if someone could take this as soon as possible.

I found this bug today and spent some time preparing to fix it. It turns out that it has been fixed here. I cried
