### ISSUE TITLE
using Roaring64Bitmap in Spark

### ISSUE THREAD

**Issue by styleNie** [RoaringBitmap/RoaringBitmap#443]
hi,I encountered a problem when using Roaring64Bitmap in Spark, the details are as follows,
spark  version 2.4.5,
Scala version 2.11.12

first
```
./spark-shell
scala> import org.roaringbitmap.longlong.Roaring64Bitmap
<console>:23: error: object Roaring64Bitmap is not a member of package org.roaringbitmap.longlong
       import org.roaringbitmap.longlong.Roaring64Bitmap
              ^
```

then 

```
./spark-shell --jars ./RoaringBitmap-0.9.8.jar
scala> import org.roaringbitmap.longlong.Roaring64Bitmap
import org.roaringbitmap.longlong.Roaring64Bitmap

scala> val res1 = new Roaring64Bitmap()
res1: org.roaringbitmap.longlong.Roaring64Bitmap = {}
scala> res1.add(16L)
java.lang.NoSuchMethodError: org.roaringbitmap.ArrayContainer.add(C)Lorg/roaringbitmap/Container;
  at org.roaringbitmap.longlong.Roaring64Bitmap.addLong(Roaring64Bitmap.java:62)
  at org.roaringbitmap.longlong.Roaring64Bitmap.add(Roaring64Bitmap.java:599)
  ... 49 elided

```

I find that spark-2.4.5 dependents  Roaring64Bitmap-0.7.45,  so how can I using Roaring64Bitmap-0.9.8 in spark-2.4.5

**Comment by lemire** [comment]
It seems that you want to use a class that was introduced in later version of the RoaringBitmap library, within a setup where you have the earlier version of the library. We cannot retroactively add features to a previous version of the library. By design, these versions are immutable. I removed the bug label, I do not think that this can be qualified as a bug.

Have you considered updating the RoaringBitmap library you are using? If you would like spark to use a more recent version of RoaringBitmap, shouldn't you take this with them? We do not control which version spark uses.

If there is something else you think we should do, please be specific.
