### ISSUE TITLE
Assertions Not Evaluated At Runtime By Default

### ISSUE THREAD

**Issue by Maithem** [RoaringBitmap/RoaringBitmap#462]
**Describe the bug**
There are many `assert` statements but during runtime assert checking is disabled by default. Is this by design?

Since most of the assertions are arithmetic expressions I don't expect the overhead to be significant. We can try to quantify it, but I think its worth having assertions enabled by default. Assertions can be enabled per JVM, but that will turn on assertion checking for everything, which might not be desirable. 

**RoaringBitmap version:**

master as of b4172eb34f4aa109974f5255cef26064d84c4db9

**Comment by blacelle** [comment]
We may ensure assertions are enabled in tests (if not already done). Else, I'm fine sticking with standard Java assertions and their standard/expected by most behavior.

**Comment by richardstartin** [comment]
This is the point of assert statements and precisely why they were added - to be able to assert about state without making it observable to a test framework. Just like we don't bundle the tests with the release, we don't want the asserts to be enabled at runtime. Assertions are always enabled in test suites. None of the asserts are there to _prevent_ incorrect behaviour, but to assert about preconditions and loop invariants as we would do in tests.

As an aside, asserts can actually be enabled at much finer granularity than per JVM; they can be enabled via the `ClassLoader` for every class loaded by that `ClassLoader` or at the package or class level. 

Despite the added bytecode weight which can interfere with inlining heuristics on HotSpot, there are real advantages to using asserts over other kinds of "sanity check", because they are guarded by a `private static final` flag variable set from the `ClassLoader` settings during class loading, so if asserts are disabled, once the code gets JIT compiled, they are constant folded away and it's as if they were never there.

**Comment by lemire** [comment]
I believe that you can enable the assertions in your own systems if you would like. If that is not the case, please report the issue.  If it is software under your control, then you can judge the effect on assertions and how to recover from errors, and so forth.

Requiring that everyone gets these classes with assertions enabled by default goes against what I consider the intended usage of Java assertions.

A few additional comments:

1. There are very few bugs in this library. If you track the bugs, you will notice that they all tend to appear in the 'recent/experimental' features, such as 64-bit Roaring Bitmap. And there is a good reason for that: the library has been used in production systems for years. Several companies use Roaring bitmaps in production for critical servicxes. This means that we did caught most of the important bugs already. With @richardstartin, we debated what to do with new code that might not have undergone as much testing as we would like. I do not think we arrived at a good solution. However, I would generally advise you to treat recent features with more suspicion than features that have been around for years. In particular, the 64-bit Roaring bitmaps which are very much experimental should be used with care. It is not just bugs that you have to be concerned about but also performance issues. It is simply the fact that when we have less experience with a code base, there are more issues to be found.
2. We can always improve the code quality but I doubt asserts help much in this respect. Rather what we most need is fuzz testing. This would be especially important for the 64-bit Roaring bitmaps. That would require some implementation effort, but one would almost surely catch hard-to-find bugs. The great thing about fuzz testing is that all it requires is implementation effort: you do not need to sacrifice performance.

Cheers!
