### ISSUE TITLE
Can't find version 0.9.41 in the Maven repository

### ISSUE THREAD

**Issue by coderzc** [RoaringBitmap/RoaringBitmap#625]
**Describe the bug**
Can't find version 0.9.41 in the Maven repository

**To Reproduce**
https://repo1.maven.org/maven2/org/roaringbitmap/RoaringBitmap/

**RoaringBitmap version:**

Please report bugs after testing the latest version of the library. If you are using an older version of the library, please explain.

Make sure to compare your version against the latest available version at https://mvnrepository.com/artifact/org.roaringbitmap/RoaringBitmap

**Java version:**

Please tell us which Java version you are using.

**Comment by lemire** [comment]
This is not a bug on our part. The release was done. We simply cannot create a release without uploading the artefacts, if we fail to do so, the release process abort. The problem is with the maven repository. It is shoddy software.

I will issue a new release. That's all I can do.

I recommend you do not depend on the maven repository. Create your own.

**Comment by lemire** [comment]
A release was issued.

Please note that we have no control over the maven repository. It routinely loses artefacts. It is a slow/lossy system.
