### ISSUE TITLE
Seeing null element in highLowContainer

### ISSUE THREAD

**Issue by noppanit** [RoaringBitmap/RoaringBitmap#645]
We're using Roaringbitmap in one of our application and sometimes we're seeing NullPointerException when doing `or` operation.

``` java
RoaringBitmap response = ParallelAggregation.or(bitmaps);
```

After investigating further we found that `bitmaps` has null value in there which should have been only just one element in there because we're using `or` and `andNot` to `add` or `remove` element from the bitmap

This is what we're doing

``` java
    public static RoaringBitmap toNewBitmapWithItem(RoaringBitmap bitmap, int item)
    {
        if (bitmap == null) {
            return RoaringBitmap.bitmapOf(item);
        }

        if (bitmap.contains(item)) {
            return bitmap;
        } else {
            return RoaringBitmap.or(bitmap, RoaringBitmap.bitmapOf(item));
        }
    }

    public static RoaringBitmap toNewBitmapWithoutItem(RoaringBitmap bitmap, int item)
    {
        if (bitmap == null) {
            return null;
        }
        if (!bitmap.contains(item)) {
            return bitmap;
        } else {
            return RoaringBitmap.andNot(bitmap, RoaringBitmap.bitmapOf(item));
        }
    }
```

From the debug I'm seeing this

![Screen Shot 2023-07-21 at 2 48 28 PM](https://github.com/RoaringBitmap/RoaringBitmap/assets/638379/4eae19c6-ca24-4795-b072-627f6eb166e5)

Which is showing that the container has two elements and one of them is null which is causing NullPointerException. I'm new to RoaringBitmap so I'm not sure how can `bitmaps` has two elements or it even has `null` element in the first place.

We're using version 0.9.15 and JDK

```
openjdk version "11.0.17" 2022-10-18 LTS
OpenJDK Runtime Environment (build 11.0.17+11-LTS)
OpenJDK 64-Bit Server VM (build 11.0.17+11-LTS, mixed mode)
```

Thanks.

**Comment by lemire** [comment]
This is not a valid bug report. You need to provide a reproducible test case.

You give two functions but you do not provide the data and code that you used. 

It is most likely that the bug is in your own code. It is possible that you found a new bug in our library but you need to provide evidence that it is so.

Right now, you are not providing use with code that would trigger the issue. This means that nobody can reasonably examine your issue.



Please write a short single-threaded program that builds the data that is in your bitmaps and run the functions that cause a problem.

I am closing the issue. Please reopen with a reproducible test case.
