### ISSUE TITLE
Travis tests fail with "Killed" when testing iterators with version 0.6.0

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#75]
Current travis tests are failing...

https://travis-ci.org/RoaringBitmap/RoaringBitmap/jobs/107318647

It fails here...

https://github.com/RoaringBitmap/RoaringBitmap/blob/master/src/test/java/org/roaringbitmap/buffer/TestMemoryMapping.java#L181-L193

**Comment by gssiyankai** [comment]
Fixed!

**Comment by lemire** [comment]
@gssiyankai 

Congratulations. For the record, can you document the fix (briefly).

**Comment by gssiyankai** [comment]
The issue was due to a lack of memory: in some tests, static bitmaps are instantiated and they are requiring more memory than available by default on the travis environment. I just increased the heap size to fix that.
Why did it occur after the upgrade to java 7 ? I don't really know... What I know for sure is that memory management is different on java 7 and I know from experience that the jvm 7 is usually requiring more memory.
Anyway, I believe it is a good practice to set the heap size in your testing strategy. It helps to have the same results on different testing environments. It's more complicated to fix a bug that you cannot always reproduce.
