### ISSUE TITLE
Support skip the NULL value when building RangeBitmap

### ISSUE THREAD

**Issue by Tan-JiaLiang** [RoaringBitmap/RoaringBitmap#752]
The range bitmap implementation is great and I would like to use it in OLAP system for file skipping.  I have a problem that I would like the community to help me with.

How should I handle the NULL value when building a range bitmap?

**Comment by richardstartin** [comment]
hi @Tan-JiaLiang, you can't represent null directly in a range bitmap, the data structure only knows about integer values. It can store other types by encoding those types as integer values so that sort order is preserved. For example, in Apache Pinot, there are range indexes on floating point values (see [here](https://github.com/apache/pinot/blob/4909b24a23fedf833fa805aad8d059b95aff754a/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/FPOrdering.java#L21)) but also on dictionaries where sort order is preserved. To represent null, you could add 1 to every value you store, and represent null as 0. You'd need to apply the same transformation when querying the data structure. 

This may seem a little cumbersome but this is a very low level API designed for a particular database index, and such encodings belong outside the project.

**Comment by Tan-JiaLiang** [comment]
@richardstartin I got it and thanks for your explain.
