### ISSUE TITLE
Support for integers larger or equal than 1<<31 is buggy/untested

### ISSUE THREAD

**Issue by lemire** [RoaringBitmap/RoaringBitmap#79]
The intention of the library is to consider integers as unsigned. So -1 should be considered as 4294967295.

Currently, this is not properly tested and generally unsafe. Only positive integers can be used safely.

We should improve this.

**Comment by owenkaser** [comment]
I have added some more unit tests and fixed things so that ranges are based on longs, and hence can include the -1 integer which is otherwise out of reach for [inclusive,exclusive) bounds as used.  The old int  range methods are left but deprecated.  Their semantics may have changed with some strange cases involving ranges outside of [0, 2^31).    I'm not sure that the testing is strong enough that this issue is totally resolved, but it's now closer.    The relevant branch is feature/long-for-ranges

**Comment by lemire** [comment]
Fixed thanks to @owenkaser 

see release 0.6.15
